//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDII_PF_JorgeIsaacLópezV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditoria_pagos
    {
        public int id_auditoria { get; set; }
        public Nullable<int> id_pago { get; set; }
        public string accion { get; set; }
        public Nullable<decimal> monto_anterior { get; set; }
        public Nullable<decimal> monto_nuevo { get; set; }
        public string estado_anterior { get; set; }
        public string estado_nuevo { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha_auditoria { get; set; }
    }
}
