//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDII_PF_JorgeIsaacLópezV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Citas()
        {
            this.Tratamientos = new HashSet<Tratamientos>();
        }
    
        public int id_cita { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
        public string diagnostico { get; set; }
        public int id_doctor { get; set; }
        public int id_paciente { get; set; }
        public int id_hospital { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    
        public virtual Doctores Doctores { get; set; }
        public virtual Hospitales Hospitales { get; set; }
        public virtual Pacientes Pacientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tratamientos> Tratamientos { get; set; }
    }
}
