//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDII_PF_JorgeIsaacLópezV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int id_pago { get; set; }
        public int id_paciente { get; set; }
        public Nullable<int> id_tratamiento { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal monto { get; set; }
        public string metodo_pago { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    
        public virtual Pacientes Pacientes { get; set; }
        public virtual Tratamientos Tratamientos { get; set; }
    }
}
