//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDII_PF_JorgeIsaacLópezV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_citas_completas
    {
        public int id_cita { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
        public string diagnostico { get; set; }
        public string estado { get; set; }
        public string doctor { get; set; }
        public string especialidad { get; set; }
        public string paciente { get; set; }
        public string hospital { get; set; }
        public string doctor_identificacion { get; set; }
        public string paciente_identificacion { get; set; }
    }
}
