//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDII_PF_JorgeIsaacLópezV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_tratamientos_medicamentos
    {
        public int id_tratamiento { get; set; }
        public string tratamiento_descripcion { get; set; }
        public decimal costo_tratamiento { get; set; }
        public Nullable<System.DateTime> fecha_tratamiento { get; set; }
        public System.DateTime fecha_cita { get; set; }
        public string diagnostico { get; set; }
        public string paciente { get; set; }
        public string doctor { get; set; }
        public string medicamento { get; set; }
        public int cantidad { get; set; }
        public decimal costo_unidad { get; set; }
        public Nullable<decimal> costo_medicamentos { get; set; }
        public string paciente_identificacion { get; set; }
        public string doctor_identificacion { get; set; }
    }
}
